#!/bin/bash
TOUT=0
FREQ=145.175M
CONF=/home/pi/direwolf.conf
while getopts t:c:f: option
 do
  case "${option}"
  in
   t) TOUT=${OPTARG};;
   c) CONF=${OPTARG};;
   f) FREQ=${OPTARG};;
  esac
 done
rtl_fm -N -f $FREQ - | /usr/local/bin/direwolf -t $TOUT -c $CONF
