#!/bin/bash
#
CONFDIR=$HOME/dconf
SAMPDIR=$CONFDIR/sample
option="o"
#
cmda="ls -al $CONFDIR/*conf* "
cmdb="cat $HOME/direwolf.conf"
cmdc="direconf"
cmdd="sudo service direwolf stop"
cmde="sudo service direwolf start"
cmdf="sudo service direwolf restart"
cmdg="copy samples to config directory"
cmdh="link tnc"
cmdi="link digi"
cmdj="link igate"
cmdk="link gbeacon"
cmdl="link pbeacon"
cmdm="direwolf -t 0 -c direwolf.conf" 

function promotesample {
ls -1 $SAMPDIR|grep conf > /tmp/samplist
for f in `cat /tmp/samplist`
do
 correct = "n"
 if [ -f $CONFDIR/$f ]
  then
   echo -e "$CONFDIR/$f exists replace ?\c"
  else
   echo -e "Copy sample $f to dconf folder ?\c"
 fi
 read ans
 if [ -z $ans ] ; then
  ans="n"
 fi
 if [ $ans = "Y" ] ; then
  cp $SAMPDIR/$f $CONFDIR
 fi
done
}


function linkfile {

if [ -e $CONFDIR/direwolf.conf.$type ] ; then
if [ -e $HOME/direwolf.conf ] ; then
  if [ -h $HOME/direwolf.conf ] ; then
    echo "direwolf.conf is linked "
    ls -l direwolf.conf
  elif [ -f $HOME/direwolf.conf ] ; then
    echo "direwolf.conf is not linked"
  fi  
rm $HOME/direwolf.conf
else
  echo "no file here?"
fi  
ln -s $CONFDIR/direwolf.conf.$type $HOME/direwolf.conf
fi
}

while [ $option != "q" ] ; do
 echo ""
 echo "a) $cmda"
 echo "b) $cmdb"
 echo "c) $cmdc"
 echo "d) $cmdd"
 echo "e) $cmde"
 echo "f) $cmdf"
 echo "g) $cmdg"
 echo "h) $cmdh"
 echo "i) $cmdi"
 echo "j) $cmdj"
 echo "k) $cmdk"
 echo "l) $cmdl"
 echo "m) $cmdm"
     
 
 echo "q) quit this menu"
 echo ""
 echo -e "Enter option :\c"
 read ans
 if [ -z $ans ] ; then
  ans="$option"
 fi
 option="$ans"
 case $option in
  a) $cmda ;;
  b) $cmdb ;;
  c) $cmdc ;;
  d) $cmdd ;;
  e) $cmde ;;
  f) $cmdf ;;
  g) promotesample ;;
  h) typef="tnc"
     linkfile ;;
  i) typef="digi"
     linkfile ;;
  j) typef="igate"
    linkfile;;
  k) typef="gbeacon"
    linkfile;;
  l) typef="pbeacon"
     linkfile;;
  m) $cmdm ;;
  q) echo "good bye"
 esac
done

