#!/bin/bash
user="NOCALL"
term="1"
passcode="12345"
loclat="33^51.43S"
loclon="151^12.91E"
gpioptt="22"
gpiodcd="23"

blank=""
correct="n"

function checkval () {
ERRSTR="\n Bad format  nn^nn.nn[SN]  33^15.55S nnn^nn.nn[EW]\n"
chkstr=$1
chklen=${#chkstr}
chkdeg=`expr index "$chkstr" ^`
chkdegd=`expr index "$chkstr" .`
chksign=`expr index "$chkstr" [ENSW]`
chksigx=`expr index "$chkstr" [EN]`
degindex=`expr $chkdeg - 1`
minindex=`expr $chkdeg + 1`
minlength=`expr $chklen - $minindex`
minval=`expr substr $chkstr $minindex $minlength`
decdeg=${chkstr:0:$degindex}
decdegs=""
if [ "$chksigx" -ne "$chklen" ]
then
  decdegs="-"
fi
decmin=`echo "scale = 3 ; $minval / 60.00 " | bc`
echo " $1 $chkstr $chklen $chkdeg $chkdegd $chksign mi $minindex ml $minlength mv $minval dm $decmin dd $decdegs"
returndec="$decdegs$decdeg$decmin"
if [ "$chklen" -ne "$chksign" ]
then
   echo $ERRSTR
elif [ "$chkdegd" -le $chkdeg ]
then
  echo $ERRSTR
elif [ "$chkdeg" -eq "0" ]
then
  echo $ERRSTR
fi
}


function paramecho {
echo "Params are Callsign $user Terminal $term creating $user-$term"
echo " APRSIS passcode $passcode"
echo "lat is $loclat  lon is $loclon"
echo "gpio BCM DCD $gpiodcd  PTT $gpioptt "
echo ""
}


function getparam {
 echo -e "Valid Callsign [e.g. VK2ABC] [$user]\c"
 read usern
 if [ -z $usern ] ; then
  usern="$user"
 fi
 user=${usern^^}
#
 echo -e "Terminal number [e.g. 1] [$term]\c"
 read termn
 if [ -z $termn ] ; then
  termn="$term"
 fi
 term="$termn"
#
 passcode=`~/VK2BV_Direwolf/bin/keygen.py "$user"`
 echo "Passcode is unique for your Callsign "
 echo -e "Passcode for [$user] calculated as [$passcode] "
 echo -e "APRSIS Passcode number [$passcode]\c"
 read passcoden
 if [ -z $passcoden ] ; then
  passcoden="$passcode"
 fi
 passcode="$passcoden"
#
 echo "lat and long for your igate location"
 echo "Format is deg^MM.MMS  use the aprs.is google map to get the value"
 echo -e "lat value [e.g. 33^51.12S] [$loclat]\c"
 read loclatn
 if [ -z $loclatn ] ; then
  loclatn="$loclat"
 fi
 loclat="$loclatn"
 checkval $loclat
 decloclat=$returndec
 echo -e "lon value [e.g. 151^51.12E] [$loclon]\c"
 read loclonn
 if [ -z $loclonn ] ; then
  loclonn="$loclon"
 fi
 loclon="$loclonn"
 checkval $loclon
 decloclon=$returndec
#
 echo "GPIO pin selection"
 echo "Uses the BCM number for the PTT signal and DCD"

 echo -e "ptt value [e.g. pin 15 BCM 22] [$gpioptt]\c"
 read gpiopttn
 if [ -z $gpiopttn ] ; then
  gpiopttn="$gpioptt"
 fi
 gpioptt="$gpiopttn"
#
echo -e "dcd value e.g. pin 14 BCM [$gpiodcd]\c"
 read gpiodcdn
 if [ -z $gpiodcdn ] ; then
  gpiodcdn="$gpiodcd"
 fi
 gpiodcd="$gpiodcdn"


}

function writesed {
 echo ""
mkdir dconf
mkdir dconf/sample
cat << EOF > dconf/sample/direwolf.hdr

## Device Section
ADEVICE plughw:1,0
ACHANNELS 1
## Channel
CHANNEL 0
MYCALL $user-$term
MODEM 1200
PTT GPIO $gpioptt
DCD GPIO $gpiodcd
AGWPORT 8000
KISSPORT 8001
##
EOF
cp dconf/sample/direwolf.hdr dconf/sample/direwolf.conf.tnc
cp dconf/sample/direwolf.hdr dconf/sample/direwolf.conf.pbeacon
cp dconf/sample/direwolf.hdr dconf/sample/direwolf.conf.gbeacon
cp dconf/sample/direwolf.hdr dconf/sample/direwolf.conf.igate
cp dconf/sample/direwolf.hdr dconf/sample/direwolf.conf.digi
cp dconf/sample/direwolf.hdr dconf/sample/direwolf.conf.testbeac


cat << EOF >> dconf/sample/direwolf.conf.pbeacon
## Fixed Position Beacon

PBEACON delay=1  every=30 overlay=S symbol="digi" lat=$loclat long=$loclon power=10 height=20 gain=4 comment="Test Direwolf Node"
EOF
#
cat << EOF >> dconf/sample/direwolf.conf.gbeacon
## Tracker uncomment this if using the GPS
GPSD
SMARTBEACONING 50 2:00 5 15:00 0:15 20 255
EOF
#
cat << EOF >> dconf/sample/direwolf.conf.igate
## Igate
IGSERVER sydney.aprs2.net
IGLOGIN $user-$term $passcode
PBEACON sendto=IG delay=0:30 every=60:00 symbol="igate" overlay=R lat=$loclat long=$loclon
EOF
#
cat << EOF >> dconf/sample/direwolf.conf.digi
## Digipeater options

PBEACON delay=1  every=30 overlay=S symbol="digi" lat=$loclat long=$loclon power=10 height=20 gain=4 comment="Test Direwolf Node"
#
DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$|^TEST$ ^WIDE[12]-[12]$ TRACE
#
EOF
#
cat << EOF >> dconf/sample/direwolf.conf.custom
PBEACON delay=1  every=60 overlay=S symbol="digi" lat=$loclat long=$loclon power=20 height=20 gain=4 comment="Test Direwolf Node"
DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$|^TEST$ ^WIDE[12]-[12]$ TRACE
FILTER  0  0  ( r/$decloclat/$decloclon/20 & ! d/* )

## Igate
IGSERVER sydney.aprs2.net
IGLOGIN  $user-$term $passcode
PBEACON sendto=IG delay=0:30 every=60:00 symbol="igate" overlay=R lat=$loclat long=$loclon
IGTXVIA 0 WIDE2*
#IGFILTER b/NEUTBA/SYD*/NMW*/
FILTER IG 0 t/mwn & ! b/VK2RHR*
IGTXLIMIT 4 8## Igate
EOF
#

cat << EOF >> dconf/sample/direwolf.conf.testbeac
## Fixed Position Beacon

PBEACON delay=0:30  every=0:30 overlay=S symbol="digi" lat=$loclat long=$loclon power=10 height=20 gain=4 comment="Test Direwolf Node"
EOF
#


}
function writesdr {
 echo ""
#mkdir dconf
#mkdir dconf/sample
cat << EOF > dconf/sample/direwolfsdr.hdr

## Device Section
ADEVICE stdin null
ARATE 24000
## Channel
CHANNEL 0
MYCALL $user-$term
##
EOF
cp dconf/sample/direwolfsdr.hdr dconf/sample/direwolf.conf.sdr

cat << EOF >> dconf/sample/direwolf.conf.sdr
## Igate
IGSERVER sydney.aprs2.net
IGLOGIN $user-$term $passcode
PBEACON sendto=IG delay=0:30 every=60:00 symbol="igate" overlay=R lat=$loclat long=$loclon
EOF
#

}

paramecho
while [ $correct != "Y" ] ; do
 getparam
 paramecho
 echo -e " If the values are correct enter "Y"  [$correct]\c"
 read ans
 if [ -z $ans ] ; then
  ans="n"
 fi
 if [ $ans = "Y" ] ; then
  correct="Y"
  paramecho >> /home/pi/paramecho.txt
  writesed
  writesdr
 fi
done
